apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      serviceAccountName: default # Connects your Pod to the DynamoDB IAM role
      containers:
      - name: auth-container
        # Use the specific tag or latest; GitHub Actions will handle the update
        image: 589578576300.dkr.ecr.us-east-2.amazonaws.com/project-app:latest 
        ports:
        - containerPort: 8080 # Matches your "Server is running on port 8080" log
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: LoadBalancer 
  selector:
    app: auth-app
  ports:
    - protocol: TCP
      port: 80         # The port you type into your browser (http://URL:80)
      targetPort: 8080 # The port inside the container the traffic is sent to